### ISSUE TITLE
enhancement idea

### ISSUE THREAD

**Issue by 1upses** [DO-Ui/bombparty-bot#4]
I made a script that allows you to get better games while playing with bots by only writing long words, come check it out, you might like it

https://github.com/1upses/bombparty-bot-enhancer

**Comment by 1upses** [comment]
it's a simple script but it's so much fun to see people's reaction to this

**Comment by DO-Ui** [comment]
I may implement longer words in v2 but as of now, I have sorta stopped working on this project.
Some things I plan for v2 (if i ever work on this again):
longer words
extra lives (getting all the letters on the side of the screen)
selenium (so you don't need to touch anything)
