### ISSUE TITLE
Typing random words

### ISSUE THREAD

**Issue by ItsEliot** [DO-Ui/bombparty-bot#5]
It just types random words not the ones with the letters in it, and also at the top of the game where it says "English" it keeps thinking that is the word. Any fix?

**Comment by DO-Ui** [comment]
It could be a problem with it trying to copy the text from the wrong location, when it doesn't copy any text it sometimes spits out random words. I will add a program that you can use to get the correct X and Y position of the letters on the screen

**Comment by DO-Ui** [comment]
I believe that should be the fix, however, if this problem persists open another issue and provide more details.
